//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyCalc.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Autocomplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Autocomplete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyCalc.Localization.Autocomplete", typeof(Autocomplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value.
        /// </summary>
        public static string abs {
            get {
                return ResourceManager.GetString("abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse cosine.
        /// </summary>
        public static string acos {
            get {
                return ResourceManager.GetString("acos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer of the last equation.
        /// </summary>
        public static string ans {
            get {
                return ResourceManager.GetString("ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse sine.
        /// </summary>
        public static string asin {
            get {
                return ResourceManager.GetString("asin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse tangent.
        /// </summary>
        public static string atan {
            get {
                return ResourceManager.GetString("atan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine in radians.
        /// </summary>
        public static string cos {
            get {
                return ResourceManager.GetString("cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic cosine.
        /// </summary>
        public static string cosh {
            get {
                return ResourceManager.GetString("cosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert radians to degrees.
        /// </summary>
        public static string deg {
            get {
                return ResourceManager.GetString("deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.14159....
        /// </summary>
        public static string pi {
            get {
                return ResourceManager.GetString("pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert degrees to radians.
        /// </summary>
        public static string rad {
            get {
                return ResourceManager.GetString("rad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine in radians.
        /// </summary>
        public static string sin {
            get {
                return ResourceManager.GetString("sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic sine.
        /// </summary>
        public static string sinh {
            get {
                return ResourceManager.GetString("sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent in radians.
        /// </summary>
        public static string tan {
            get {
                return ResourceManager.GetString("tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic tangent.
        /// </summary>
        public static string tanh {
            get {
                return ResourceManager.GetString("tanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.14159....
        /// </summary>
        public static string π {
            get {
                return ResourceManager.GetString("π", resourceCulture);
            }
        }
    }
}
